# Generated by Django 4.2.5 on 2024-01-02 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('cat_img', models.FileField(blank=True, null=True, upload_to='media')),
            ],
            options={
                'db_table': 'Category',
            },
        ),
        migrations.CreateModel(
            name='Sub_Categorys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub', models.CharField(max_length=50)),
                ('subcats', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='lur_nursery.category')),
            ],
            options={
                'db_table': 'Sub_Categorys',
            },
        ),
        migrations.CreateModel(
            name='Sub_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcat', models.CharField(max_length=50)),
                ('sub_img', models.FileField(blank=True, null=True, upload_to='media')),
                ('names', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='lur_nursery.category')),
            ],
            options={
                'db_table': 'Sub_Category',
            },
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=3, max_digits=10)),
                ('item_img', models.FileField(blank=True, null=True, upload_to='media')),
                ('conditions', models.CharField(max_length=50)),
                ('offer', models.CharField(max_length=50)),
                ('sub', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='lur_nursery.category')),
            ],
            options={
                'db_table': 'Items',
            },
        ),
    ]
