# Generated by Django 4.2.5 on 2024-01-02 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lur_nursery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='discount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
    ]
