# Generated by Django 4.2.5 on 2024-01-02 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lur_nursery', '0002_items_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='description',
            field=models.TextField(default=0, max_length=5000),
        ),
        migrations.AlterField(
            model_name='items',
            name='sub',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='lur_nursery.sub_categorys'),
        ),
        migrations.AlterField(
            model_name='sub_categorys',
            name='subcats',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='lur_nursery.sub_category'),
        ),
    ]
