# Generated by Django 4.2.5 on 2024-01-03 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lur_nursery', '0003_items_description_alter_items_sub_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='price',
            new_name='dis_price',
        ),
        migrations.AddField(
            model_name='items',
            name='org_price',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
    ]
